"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    # Heroku: accept the app's .herokuapp.com domain and any custom domain.
    # config() returns '' by default so the filter(None, ...) removes empty strings.
    *filter(None, [
        config('HEROKU_APP_NAME', default=''),
        # If you set HEROKU_APP_NAME=smartseason-api, this becomes
        # 'smartseason-api.herokuapp.com' via the line below.
    ]),
]
# Append the full .herokuapp.com hostname when HEROKU_APP_NAME is present.
_heroku_app = config('HEROKU_APP_NAME', default='')
if _heroku_app:
    ALLOWED_HOSTS.append(f'{_heroku_app}.herokuapp.com')

# --- CORS ---
# Allow the Vite dev server to reach the Django API (local development).
# In production, FRONTEND_URL is the deployed Vercel URL.
_frontend_url = config('FRONTEND_URL', default='')
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    *filter(None, [_frontend_url]),
]
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    # django-filter enables structured field filtering on list endpoints.
    # Example: GET /api/fields/?is_active=true&crop_type=Maize
    # Registering it here lets Django find its app config and templates.
    'users',
    'fields',
    'monitoring',
    # The monitoring app holds FieldReport — the core data collection model.
    # Agents submit reports here; coordinators read them.
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # WhiteNoise must be directly after SecurityMiddleware so it can serve
    # compressed static files before any other middleware runs.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# In production (Heroku) DATABASE_URL is set as an environment variable and
# dj_database_url parses the full connection string into Django's expected dict.
# Locally (dev) DATABASE_URL is not set, so we fall back to the individual
# DB_* variables from the .env file — keeping local development unchanged.

_DATABASE_URL = config('DATABASE_URL', default='')

if _DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
            # conn_max_age=600: keep each DB connection open for 10 minutes
            # (persistent connections) to avoid the overhead of reconnecting
            # on every request — especially important on Heroku eco dynos.
            # ssl_require=True: Supabase requires SSL on all connections.
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT', cast=int),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# STATIC_ROOT: the directory collectstatic writes all static files into.
# WhiteNoise then serves files from this directory in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise storage: compresses static files (gzip + brotli) and appends
# a content hash to filenames so browsers cache them aggressively.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# --- Django REST Framework global configuration ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Every request now tries to extract a JWT from the Authorization header.
        # Header format: Authorization: Bearer eyJhbGci...
        # If a valid token is found, request.user is populated automatically.
        # If no token or an invalid token is sent, request.user is AnonymousUser.
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        # Global default: every endpoint requires a logged-in user UNLESS
        # the view explicitly sets permission_classes = [AllowAny].
        # RegisterView already does this — it won't break after this change.
    ],

    # --- Filtering ---
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        # Enables ?field=value filtering on any ViewSet that declares filterset_fields.
        # Example: GET /api/fields/?is_active=true&crop_type=Maize
        # DjangoFilterBackend does exact-match (and range/choice) filtering.

        'rest_framework.filters.SearchFilter',
        # Enables ?search=<term> free-text search across declared search_fields.
        # Example: GET /api/fields/?search=nakuru
        # Uses icontains (case-insensitive substring match) by default.

        'rest_framework.filters.OrderingFilter',
        # Enables ?ordering=<field> and ?ordering=-<field> (descending) sorting.
        # Example: GET /api/fields/?ordering=-created_at
        # Only fields listed in ordering_fields on the view are allowed.
    ],

    # --- Pagination ---
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.StandardResultsPagination',
    # Points to our custom pagination class in config/pagination.py.
    # Applies to every list endpoint that returns a queryset.

    'PAGE_SIZE': 20,
    # Default number of items per page when the client does not specify ?page_size=.
    # Our StandardResultsPagination allows the client to override this up to max_page_size=100.
}


# --- SimpleJWT configuration ---
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=60),
    # Access tokens expire after 60 minutes.
    # After expiry, the client must use the refresh token to get a new one.
    # Short lifetime limits damage if a token is stolen — it expires quickly.

    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Refresh tokens last 7 days.
    # After 7 days the user must log in again with email + password.

    'ROTATE_REFRESH_TOKENS': True,
    # Every time the client calls /api/auth/refresh/, they get a new refresh token
    # in addition to a new access token. The old refresh token is invalidated.
    # This is a security improvement — a stolen refresh token can only be used once.

    'AUTH_HEADER_TYPES': ('Bearer',),
    # The prefix expected in the Authorization header.
    # Authorization: Bearer eyJhbGci...
    # 'Bearer' is the OAuth2 standard — all modern API clients use this.
}
