# Generated by Django 5.2.13 on 2026-04-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_field_expected_emergence_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='expected_farm_prep_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='realized_farm_prep_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
