# Generated by Django 5.2.13 on 2026-04-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_field_expected_farm_prep_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='current_stage',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('farm_prepped', 'Farm Prepped'), ('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], default='not_started', max_length=20),
        ),
    ]
