# Generated by Django 5.2.13 on 2026-04-23 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('crop_health', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('soil_moisture', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pest_observed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='report_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='fields.field')),
            ],
            options={
                'verbose_name': 'Field Report',
                'verbose_name_plural': 'Field Reports',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
